### ISSUE TITLE
Recording site selection method

### ISSUE THREAD

**Issue by juliencarponcy** [open-ephys-plugins/neuropixels-pxi#14]
Hi,

Apart from within the GUI by clicking, I do not find documentation on how to edit configuration files for different recording sites selections. The closest thing I could find, I guess, is that in the config file:

<PROBE visualizationMode="0" filterCutIndex="1" filterCut="ON" referenceChannelIndex="1" referenceChannel="Ext" lfpGainIndex="2" lfpGainValue="125x" apGainIndex="3" apGainValue="250x" ZoomOffset="153" ZoomHeight="100" flex_version="1.2" flex_part_number="NP2_FLEX_0" hs_version="5.1" hs_part_number="NP2_HS_30" hs_serial_number="289" probe_serial_number="18194811551" port="1" bsc_serial_number="185" bsc_part_number="NP2_QBSC_00" bsc_firmware_version="1.0.151" firmware_version="1.1.128" slot="2" basestation_index="1">

**<CHANNELSTATUS E959="-2" E958="0" E957="0" E956="0" E955="0" E954="0" E953="0" E952="0" E951="0" E950="0" E949="0" E948="0" E947="0" E946="0" E945="0" E944="0" E943="0" E942="0" E941="0" E940="0"** 

etc.. Anyway we could find out which number correspond to where in the NP1.0 ? Or a repository of different configuration pre-established? I would be happy to share once i've done mine but I will first have to figure out the "pin-out" ? 

It looks like that the channel nb is indicated starting from the tip, so i guess if I activate one over 2 sequentially I will have a 2 column design (probably 1st and 3rd). Extending that reasoning, it seems to me that making some kind of tetrode/diamond pattern would require to perform a sequence like:

Skip 1 contact
Activate
Skip 2 contacts
Activate
Skip 1 contact
Activate
Skip 2 contacts
...

That also seems to differ from SpikeGLX imro tables : (0,384)(0 0 0 500 250 1)(1 0 0 500 250 1)(2 0 0 500 250 1)(3 0 0 500 250 1)(4 1 0 500 250 1)(5 1 0 500 250 1)(6 1 0 500 250 1)(7 1 0 500 250 1)(8 0 0 500 250 1)(9 0 0 500 250 1)(10 0 0 500 250 1)(11 0 0 500 250 1)(12 1 0 500 250 1)(13 1 0 500 250 1)(14 1 0 500 250 1)(15 1 0 500 250 1)(16 0 0 500 250 1)(17 0 0 500 250 1)(18 0 0 500 250 1)(19 0 0 500 250 1)(20 1 0 500 250 1)(21 1 0 500 250 1)(22 1 0 500 250 1)(23 1 0 500 250 1)(24 0 0 500 250 1)(25 0 0 500 250 1)(26 0 0 500 250 1)(27 0 0 500 250 1)(28 1 0 500 250 1)(29 1 0 500 250 1)(30 1 0 500 250 1)(31 1 0 500 250 1)(32 0 0 500 250 1)(33 0 0 500 250 1)(34 0 0 500 250 1)(35 0 0 500 250 1)(36 1 0 500 250 1)(37 1 0 500 250 1)(38 1 0 500 250 1)(39 1 0 500 250 1)(40 0 0 500 250 1)(41 0 0 500 250 1)(42 0 0 500 250 1)(43 0 0 500 250 1)(44 1 0 500 250 1)(45 1 0 500 250 1)(46 1 0 500 250 1)(47 1 0 500 250 1) ....
(http://billkarsh.github.io/SpikeGLX/help/imroTables/)

I would be grateful if you could point me at resources I may have missed, or alternatively, provide your insight of the best way(s) to perform such operations.

Thank you very much for the good work, the GUI has evolved a lot since I last used it (like a year ago). You're building a very nice piece of software !

Julien

**Comment by jsiegle** [comment]
The `CHANNELSTATUS` section is where the recording sites are configured. It uses 0-based indexing, so `E0` - `E959` correspond to electrodes 1-960, where 1 is at the tip. A value of "1" means the electrode is selected, a value of "0" means it's deselected, and a value of "-2" is for reference channels.

So, that is how you would go about editing the configuration currently. However, we are planning to make it possible to upload SpikeGLX .imro files in the near future, so stay tuned for that.

**Comment by juliencarponcy** [comment]
Thank you very much! looking forward to it
