### ISSUE TITLE
Setting.xml seems not saving the shank with multishank recording

### ISSUE THREAD

**Issue by MarineChap** [open-ephys-plugins/neuropixels-pxi#23]
Hello, I think we caught a bug when using a multishank probe in fklab lab. Or we did not use the plugin as intended ? 
We are on latest open-ephys / plugin version. 

An external IMRO file is used to configure the channelmap with a multi-shank probe, then a recording is run.
If I interpreted correctly the setting file, all shanks in the setting.xml are set to 0 while the recording is being done on different shanks.
The display in the plugin and the recording is done correctly. The problem seems to be only in the saving part of the setting file.
That causes some problems when using the spike interface to load the data. see [this issue in probeinterface package.](https://github.com/SpikeInterface/probeinterface/issues/106)

- [imro_file.txt](https://github.com/open-ephys-plugins/neuropixels-pxi/files/8688924/imro_file.txt)
- [settings.txt](https://github.com/open-ephys-plugins/neuropixels-pxi/files/8688922/settings.txt)

Also, that would be super useful to have some documentation about how the setting.xml is constructed and how to retrieve the 
data. 
Thanks !
Have a good day

**Comment by medengineer** [comment]
Hi Marine,

I ran a recording using your attached IMRO file and the generated settings file is consistent with the IMRO config. I've attached it [here](https://github.com/open-ephys-plugins/neuropixels-pxi/files/8690005/settings.txt).  

Can you confirm which version of the Neuropixels plugin you are seeing this with?

Thanks!

**Comment by MarineChap** [comment]
Hello, thank you for checking on your side. Happy it works and I will use this setting to fix ours. 

I keep you posted as soon as I heard a feedback from the doctorant working on it for the exact version. I am wondering what happened because i was super confident to be on the latest as I did a clean installation myself (removed everything/reinstalled everything from latest) two months ago. But clearly the problem is on our side.

Have a nice day.

**Comment by MarineChap** [comment]
open ephys version : 0.5.5.3
neuropix-pix version: 0.3.4-API7

**Comment by MarineChap** [comment]
I will ask the doctorant but she did 2 sessions and both are like this.

**Comment by LiesDec** [comment]
@jsiegle hi, I'm the PhD student @MarineChap talked about. 
After reinstalling the plugin I now indeed have the channel map saved in the `settings.xml` file.

However, I think there is still a small bug for the multistank probe. 
In the code ([#L1293](https://github.com/open-ephys-plugins/neuropixels-pxi/blob/de8abc9b531b1f469ed9fb442439bbd824cc5ee2/Source/UI/NeuropixInterface.cpp#L1293)) you add 250 to the y coordinate. But that is not necessary. In the x coordinate that does make sense 'cause you jump shank.

**Comment by jsiegle** [comment]
You're right, that's a mistake...we'll get that fixed before the next release.
