### ISSUE TITLE
enable to load the extended setting interface

### ISSUE THREAD

**Issue by ouardouzm** [open-ephys-plugins/neuropixels-pxi#24]
I am setting the open-ephys neuropixels PXi. when trying to open the extended setting interface it is blank. all the plugins where added and the gui detected the neuropixels PXI. could you help solve this issue thansk!

**Comment by anjaldoshi** [comment]
Hi, 

What version of the neuropixels-pxi plugin are you running? You can check the installed plugin version in the Plugin Installer. Also, do you have any probes connected to the basestation when you load the plugin into the GUI?

**Comment by ouardouzm** [comment]
I just add the plugins so it should be the last ones neuropixels PXI. No I did not have the probe when I did the install. When I open the plugin installer it does not show the plugin installed.

**Comment by ouardouzm** [comment]
I just reinstalled the plugin with the probe but still the same problem.

**Comment by anjaldoshi** [comment]
Can you make sure the probe is getting detected by the Neuropixels-PXI plugin? If it is then the plugin should show a green circle for each connected probe in the plugin editor like this:

![neuropix-pxi-01](https://user-images.githubusercontent.com/11559287/189405192-3b5abcd1-3ae0-4427-be31-6cf006addd79.png)

Also, can you send a screenshot of the GUI with the plugin loaded in the signal chain?

**Comment by ouardouzm** [comment]
No The probe is not detected.

**Comment by ouardouzm** [comment]
Hi 
update I was able to have the system detect the probe. I am using the code. I need to put the probe but I cannot find the configuration info folder in programdata or the folder where I launched the OPENEPHYS. do I have to create one

**Comment by ouardouzm** [comment]
Thanks for your support I was able to make it work.

**Comment by jsiegle** [comment]
Do you know what you did that fixed the problem in the end?
