### ISSUE TITLE
Headstage tester freezes GUI

### ISSUE THREAD

**Issue by jonahpearl** [open-ephys-plugins/neuropixels-pxi#32]
Hi -- I'm working on setting up a new Neuropixels system with open ephys. I'm running a Windows 10 machine that is relatively up to date, along with the newest plugin-GUI (0.6.6) and the newest neuropixels-PXI plugin (downloaded a few days ago). I'm using a NI 1073 and a new IMEC card for hardware, plus a standard HS NP2 for the headstage and a recently shipped headstage tester.

When I plug in the headstage tester, and drag the PXI plugin into the signal chain, I get the following output, but then everything freezes:

> [open-ephys] Creating processor with name: Neuropix-PXI
[open-ephys] Scanning for devices...
[open-ephys]   Found 1 device.
[open-ephys]   Opening device on slot 4
[open-ephys]   Opened BS on slot 4
[open-ephys]   BS firmware: 2.0169
[open-ephys]     Searching for probes...
[open-ephys] Got HS part #: NP2_HS_30
[open-ephys]       Found 1.0 single-dock headstage on port: 1
[open-ephys]   No headstage detected on port: 2
[open-ephys]   No headstage detected on port: 3
[open-ephys]   No headstage detected on port: 

After that the GUI just hangs indefinitely (> 5 minutes). I see that the tests are supposed to auto-run, but I assume they don't take >5 minutes?

If I use a real NP2 probe, everything seems to work fine, and most of the self-tests seem to pass (I didn't try every single one yet).

Any thoughts on why the headstage tester might not be working (other than if the tester itself is broken)? It lights up its little "OK" light when it's plugged in, so at least it seems to be connected.

Thanks!

**Comment by jsiegle** [comment]
Hi Jonah – We'll definitely look into why the GUI is hanging when the headstage tester is connected and push a fix for that soon. But in the meantime, you can assume that everything is fine with your headstage if you can acquire data from an actual probe. 

The headstage tested doesn't work the way you might expect, which would be to simulate data coming from a probe. Instead, it just runs a few tests and then returns. We've never used it to diagnose a problem that wasn't easier to catch by plugging in a probe.

**Comment by jsiegle** [comment]
Actually, the version with the fix is 0.6.1
