### ISSUE TITLE
Firmware update failure

### ISSUE THREAD

**Issue by Tevin-yue** [open-ephys-plugins/neuropixels-pxi#33]
I recently updated the firmware and now the PXIe acquisition module is not working. The acquisition module red light keeps on. The updated firmware versions are as follows: QBSC firmware: B176 (appears as 3.2176) and BS firmware: B169 (appears as 2.0169).  Open ephy verison is 0.6.4, neuropixel-pxi is 0.5x. HOw an I recover the old firmware?
![malfuntional module](https://github.com/open-ephys-plugins/neuropixels-pxi/assets/80507794/980b50f1-c50b-4000-98dd-8af4364aa408)
![software enviroment](https://github.com/open-ephys-plugins/neuropixels-pxi/assets/80507794/c3221d23-97ec-4d6c-aa69-f699c9638001)

**Comment by jsiegle** [comment]
Hi Tevin -- we actually just had the same thing happen with two of our basestations at the Allen Institute, and we're not sure what caused it, as we've performed dozens of successful firmware updates previously. We reached out to imec to see if they have any insight into a fix. Please don't try to update the firmware on any other basestations until we figure out what's going on.

A couple questions:
- Did both the BS and QBS firmware updates complete successfully, and did you fully power off your computer/chassis after they finished?
- What NI chassis model do you have?

**Comment by Tevin-yue** [comment]
I have changed the firmware back with spiekGLX, and now it can be recognized. The chassic I used is NI 1071.

**Comment by jsiegle** [comment]
If the card is not being recognized, you'll need to reset the firmware using the ISP button. To do this, use the following steps:
- Shut down your computer and chassis (so the power lights are completely off)
- Insert a screwdriver or other pointed object into the hole marked "ISP" (see image below). The button is a few mm inside the hole, and you should feel a gentle click when the button is depressed.
- With the ISP button depressed, restart your computer. The status light should turn green, briefly flash red, then turn green again. Once the light is continuously green, you can stop pressing the button.
- Try the firmware update again, using Open Ephys or SpikeGLX

In our experience, this procedure works most of the time, but not always. If you're not able to connect to the board after following these steps, let us know!

<img width="363" alt="ISP_button" src="https://github.com/open-ephys-plugins/neuropixels-pxi/assets/200366/168e4b5d-ebb9-417b-a4df-7da75e3d8ad6">

**Comment by Tevin-yue** [comment]
Thanks a  lot, I have tried this and it did work. Then the spiekGLX can update the firmware but not with Open Ephys. Once I open the Open Ephys the card is lost and the light turned off. Maybe the latest the firmware is not completely cpmpatible with hardware.
