### ISSUE TITLE
Issue with XML file for version `0.7`

### ISSUE THREAD

**Issue by vigji** [open-ephys-plugins/neuropixels-pxi#37]
Hi people, thanks for the awesome tools!

I'm doing some bug fix for enabled/disabled probe combination reading using `probeinteface` - see https://github.com/SpikeInterface/probeinterface/pull/308.

I have two recording `xml` files that I acquired from one rig not updated to latest `0.7`, mounting `0.6.7`, and one rig updated to `0.7`.

The curious thing is that in both I find the following in the `xml` file:

```xml
<SETTINGS>
  <INFO>
    <VERSION>0.6.7</VERSION>
   ...
```

I am sure the files are from different versions as in one - the 0.7 one - I can see te `isEnabled` attribute for the probe and in the other I cannot.

What is happening?

**Comment by jsiegle** [comment]
Thanks for taking care of that bug fix in ProbeInterface!

I think you're confusing the GUI core application version with the plugin version. The plugin version should be listed later in the settings file, and should either be 0.6.6 or 0.7.0 for Neuropixels.

**Comment by vigji** [comment]
Oh great, I was being stupid - thanks for the quick reply! :)
